pkg/config/config.go, pkg/config/config_test.go, pkg/controller/validate_config_test.go
This introduces a new config field `migrationLogLevel` for `SpiceDBCluster`:
```yaml
spec:
config:
migrationLogLevel: debug
logLevel: info
```
It allows configuring a different log level for the migration jobs vs. the spicedb pods themselves.
=> Configure log level and migration log level separately

e2e/cluster_test.go, go.mod, go.sum, pkg/apis/authzed/v1alpha1/conditions.go, pkg/cmd/run/run.go, pkg/controller/config_change.go, pkg/controller/controller.go, pkg/controller/secret_adoption.go, pkg/controller/secret_adoption_test.go
Previously, the operator would "adopt" any secret that you put in the `spec` of a `SpiceDBCluster`, even if it didn't exist. This change checks for the existence of the secret before adopting it, and writes out a condition to the status if it can't be found.
Note that the controller will poll the kube api (with backoff & respecting APF responses) indefinitely if a secret can't be found.
This PR also switches to `logr` as a part of updating `controller-idioms` to 0.4.0, but there is no external-facing change.
=> Check for secret existence 

.github/workflows/build-test.yaml, config/crds/authzed.com_spicedbclusters.yaml, e2e/cluster_test.go, e2e/postgresql.yaml, e2e/util_test.go, go.mod, go.sum, pkg/apis/authzed/v1alpha1/conditions.go, pkg/apis/authzed/v1alpha1/types.go, pkg/config/config.go, pkg/config/config_test.go, pkg/config/global.go, pkg/controller/config_change.go, pkg/controller/controller.go, pkg/controller/ensure_deployment.go, pkg/controller/ensure_deployment_test.go, pkg/controller/run_migration.go, pkg/controller/validate_config.go, pkg/controller/validate_config_test.go, pkg/crds/authzed.com_spicedbclusters.yaml, pkg/metadata/keys.go
This adds three new fields to the operator config file:
- `nodes`, a map from a hash to a particular spicedb deployment config (`tag`, `migration`, and `phase`
- `requiredEdges` a map from node hash to node hash.
- `headMigrations` a map from tag+datastore to the name of the head migration for that release
If the spec of a `SpiceDBCluster` is changed, and the currently running config matches the key of something in the `requiredEdge` map, then the node pointed to by the value of the `requiredEdge` map will be deployed instead.
Example of `SpiceDBCluster` statuses as it walks through a required update flow: https://gist.github.com/ecordell/8ede43054caa3694623a5a16a158ed38
TODO:
=> Add required update edges

pkg/config/config.go
If upgrading from a version of the operator that doesn't write the migration name into the status, the `currentMigration` will be `""` - the operator prefers this value, so it is possible to run migrations that run `spicedb migrate __` with no migration name, which will fail.
=> default target migration to `head` if it is otherwise unset

pkg/config/config.go, pkg/config/config_test.go, pkg/config/keys.go, pkg/config/keys_test.go, pkg/controller/validate_config_test.go
We are using the SpiceDB Operator and would like to have the pods monitored by our telemetry tool (DataDog) which requires setting annotations on the pod to instruct our agent on how to pull metrics out of the pod. There currently is not an option for passing annotations, however, you can pass labels.
See issue: https://github.com/authzed/spicedb-operator/issues/106
Most of our infrastructure relies on our deployments to be monitored/alerted upon, so getting this in asap would be greatly appreciated! If the preference is to go a different direction with customization, feel free to ignore, I was just hoping to follow the pattern with labels to enable the functionality.
This PR adds a new property to the `SpiceDBCluster` called `extraPodAnnotations` that mimics that of the `extraPodLabels` …
=> feat: allow custom annotations

pkg/config/config.go, pkg/config/config_test.go, pkg/controller/ensure_deployment_test.go
fixes https://github.com/authzed/spicedb-operator/issues/111
users running the repository example where stuck because the SpiceDB instance spun up had Dispatch API server disabled, but actual dispatching enabled, so `Check` requests errored out.
This adds tests to verify the untested method `ToEnvVarApplyConfiguration()` and makes sure memory datastore does not set dispatchUpstreamAddr
=> disables dispatch for memory datastore

pkg/config/config.go, pkg/controller/validate_config.go, pkg/updates/file.go, pkg/updates/file_test.go, pkg/updates/memory.go, pkg/updates/memory_test.go
This PR refactors a bit of the logic being used to traverse the UpdateGraph into methods specifically on the update graph and adds tests for them.
=> pkg/updates: move logic into graph methods

e2e/cluster_test.go, pkg/config/config.go, pkg/config/config_test.go
We added support for specifying the name of the Service Account to be created in #122, but we didn't actually set it on the pods. This fixes that and adds tests.
=> pkg/config: Set correct Serice Account on pods

.github/workflows/build-test.yaml, .github/workflows/release.yaml
The release is failing right now because `includes` is a pro-feature.
=> Switch to goreleaser-pro

goreleaser.yaml
The config was in the wrong section. 
There might be a couple more of these, since I can't easily test the GH release workflow locally
=> include `bundle.yaml` file in the GH release

.github/workflows/release.yaml, .gitignore, goreleaser.yaml
goreleaser complains about a dirty tree if we modify the `kustomization` directly.
=> Build release manifests in a .gitignored directory

.github/workflows/release.yaml, goreleaser.yaml
This got lost when refactoring the release workflow
=> install kustomizer in release workflow

default-operator-config.yaml, tools/generate-update-graph/main.go
Fixes #136 
The latest migration changed during development of the update graph feature, and was never updated.
In the future, a test suite will validate these graphs, for now, here's the status of a fresh postgres `SpiceDBCluster`:
```yaml
status:
currentMigrationHash: n7ch99h687h697h56bh566h6ch688q
image: ghcr.io/authzed/spicedb:v1.16.1
migration: drop-bigserial-ids
observedGeneration: 1
targetMigrationHash: n7ch99h687h697h56bh566h6ch688q
version:
channel: stable
name: v1.16.1
```
=> fix migration for postgres v1.14.0-v1.16.1

.github/workflows/build-test.yaml, .github/workflows/lint.yaml
I tried enabling the merge queue for this repo, but the required checks didn't run on queued PRs. 
It turns out there's a new type for merge queue events: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#merge-group
Once this merges I'll re-enable the merge queue and we can try again.
=> support merge_group event types in GHA

pkg/config/config.go
Istio, Banzai-vault and a lot of 3rd party kubernetes controllers and components requires specific annotations to set in order to work properly. While the SpiceDBCluster resource did have option to specify extra pod annotations before, it was not propagated to the migration jobs, effectively render the operator's managing migrations capability ineffective on clusters running controllers mentioned above.
This patch will simply add the specified extraPodAnnotations to the migration job's podTemplate, unlocking migration capabilities on such clusters.
Fixes: #146
=> feat: add extraPodAnnotations on migrations jobs

README.md
The documentation when giving examples of valid configs specifies the `ClusterStatus.CurrentVersion` as `currentVersion` when in reality is exposed as just `version` as defined [here](https://github.com/authzed/spicedb-operator/blob/6ebd7fd876dcde835ef4309808003edbc5dffb56/pkg/apis/authzed/v1alpha1/types.go#L151) in the code.
This updates the documentation for it to reduce confusion.
=> chore: Fix documentation for `ClusterStatus.CurrentVersion`

pkg/config/config.go, pkg/controller/ensure_deployment_test.go
This uses a stable name of `spicedb` for SpiceDB containers in generated Deployment objects.  This makes applying patches to things inside the container definitions, like resources requests, much easier.
=> Use stable name for SpiceDB containers

e2e/cluster_test.go
This decreases the time it takes for a pod to become healthy and speeds up the tests.
=> Set min connections low for tests

pkg/config/config.go, pkg/config/config_test.go
This sets the termination log path to match the kube default, so that spicedb pods report errors to the default termination log location
=> Set termination log path by default

pkg/config/config.go, pkg/config/config_test.go, pkg/controller/ensure_deployment_test.go
Is this something we'd be interested in? Makes the pod name available in the `SPICEDB_POD_NAME` environment variable via the Kubernetes downward API.
=> Set SPICEDB_POD_NAME environment variable using the downward API

pkg/apis/authzed/v1alpha1/types.go, pkg/updates/file.go, pkg/updates/file_test.go
When multiple update channels are defined, the operator now has this behavior:
- If the currently running version exists in the new channel, the new channel takes over without any fanfare. If no version is asked for explicitly, updates will be walked in the new channel.
- If the currently running version doesn't exist in the new channel, the current version will be annotated with an attribute "not in desired channel". The operator will wait until the graph is updated and an edge is found in the desired channel.
=> Support and test switching channels

pkg/config/config.go, pkg/config/config_test.go
This adds two new config fields:
```yaml
spec:
config:
projectLabels: true
projectAnnotations: true
```
When true (the default), all of the pod's labels and annotations will be available in the container at `/etc/podlabels/labels` and `/etc/podannotations/annotations`
=> Project labels and annotations into pod volumes

pkg/controller/ensure_deployment.go, pkg/controller/ensure_deployment_test.go
the previous implementation just checked if there were the desired number of ready replicas, which would be the case if a good config had been previously rolled out and then changed.
=> report errors even after an initial successful rollout

pkg/config/patch.go, pkg/config/patch_test.go
This is essentially the same bug as #226, but is triggered in a slightly different way: this relies on multiple patches interfering.
This adds a test case that reproduces the problem (which now passes).
=> fixes an array patching bug when there are multiple patches

pkg/controller/ensure_deployment.go, pkg/controller/ensure_deployment_test.go
If a migration job completely fails so that the cluster gets the MigrationFailed condition, it wouldn't be removed if the migrations were re-run and the cluster became healthy.
=> remove migrating failed condition after a successful migration run

Dockerfile.release
Switch from the default distroless image (which runs as root) to the distroless image (which runs as uid 65532)
Related to #237
=> Build from distroless/base:nonroot

CONTRIBUTING.md
=> CONTRIBUTING: sync format, legal details

.github/dependabot.yml
this add grouping to dependabot, so go mod updates come in a single PR
It also adds update configuration for github actions
=> add grouping and github-actions updates

pkg/config/config.go, pkg/config/config_test.go, pkg/controller/ensure_deployment_test.go
Adds the Kubernetes pod name to a file at `/etc/podmeta/name`. This aligns with the method we use to inject pod labels and annotations.
=> Inject pod name into volume

pkg/cmd/run/run.go
this can be useful for testing, when starting multiple operators in parallel
=> metrics: make metric namespace configurable

config/operator.yaml
After https://github.com/authzed/spicedb-operator/pull/320, memory usage increased quite a bit. While still usually within the limits already set, this commit bumps the defaults a bit to provide similar headroom to the previous defaults.
https://github.com/authzed/spicedb-operator/issues/322 tracks finding the root cause (the openapi change or the kube dependency updates), after which we can lower these defaults down again.
=> Increase default memory requests and limits

.github/workflows/release.yaml, goreleaser.yaml
- adds version to the goreleaser file
- changes deprecated `--rm-dist` to `--clean` (v2 fails instead of warning)
=> release: updates for goreleaser v2

.github/workflows/lint.yaml
codeql doesn't support running on merge queue right now, so it always errors.
=> only run codeql on pull requests

pkg/cmd/run/run.go, pkg/controller/context.go, pkg/controller/controller.go, pkg/controller/controller_test.go
The existing implementation didn't wire up the caches correctly if more than one namespace was specified. Caches are identified by the namespace they watch, so we need to construct lookup keys per-watched namespace.
This also adds a test of the namespace watch modes.
=> Fix multi-namespace watches and add a test

pkg/config/config.go, pkg/config/config_test.go
It was possible to write a patch like `spec: null` that removed fields that the controller expects to exist, even after patching, which could lead to a panic. This enforces that those required fields exist and adds tests for each created object.
Fixes #357
=> Prevent patches from patching out required fields

.golangci.yaml, pkg/apis/authzed/v1alpha1/types.go, pkg/config/config.go, pkg/config/config_test.go, pkg/controller/validate_config.go
This repo hadn't been migrated to v2 yet. This fixes that.
* Run `golangci-lint migrate`
Review. See that tests pass.
=> Fix golangci-lint config

config/rbac/role.yaml, e2e/assertions_test.go, e2e/cluster_test.go, pkg/config/config.go, pkg/config/config_test.go, pkg/controller/controller.go, pkg/metadata/keys.go
This prevents infrastructure changes from disrupting more than 1 pod in a SpiceDB cluster at a time.
Fixes CTL-874
=> Generate a PDB that protects SpiceDB replicas

pkg/config/config.go, pkg/config/config_test.go, pkg/controller/controller.go
- switch to `maxUnavailable=1` so no SpiceDB pod is ever lost when nodes are cycled
- fixes left over PDB with invalid value when scaling from >1 to =1 replicas (works in tandem with ☝🏻 )
=> switch to maxUnavailable=1 and create PDB even if replicas=1
